#!/sbin/busybox sh

. /res/customconfig/customconfig-helper

_ACTIVEPROF=`cat /data/.hybridmax/.hybridmax.profile`

case "${_ACTIVEPROF}" in
  battery)
    cp /data/.hybridmax/battery.profile /data/.hybridmax/default.profile 
    read_defaults
    read_config
    apply_config
    ;;
  balanced)
    cp /data/.hybridmax/balanced.profile /data/.hybridmax/default.profile 
    read_defaults
    read_config
    apply_config
    ;;
  performance)
    cp /data/.hybridmax/performance.profile /data/.hybridmax/default.profile 
    read_defaults
    read_config
    apply_config
    ;;
esac;
