#!/sbin/busybox sh

# $1 - "gpu_governor"
# $2 - value=
# Created By Dorimanx
# Adaptet by Hybridmax

if [ "a$2" != "a" ]; then
	gpu_governor=$2;

	case "${gpu_governor}" in
		simple)
			GPU_GOV=$(cat /sys/devices/platform/kgsl-3d0.0/kgsl/kgsl-3d0/pwrscale/trustzone/governor);
			if [ "$GPU_GOV" != "simple" ]; then
				echo "simple" > /sys/devices/platform/kgsl-3d0.0/kgsl/kgsl-3d0/pwrscale/trustzone/governor;
			fi;
		;;
		ondemand)
			GPU_GOV=$(cat /sys/devices/platform/kgsl-3d0.0/kgsl/kgsl-3d0/pwrscale/trustzone/governor);
			if [ "$GPU_GOV" != "ondemand" ]; then
				echo "ondemand" > /sys/devices/platform/kgsl-3d0.0/kgsl/kgsl-3d0/pwrscale/trustzone/governor;
			fi;
		;;
		performance)
			GPU_GOV=$(cat /sys/devices/platform/kgsl-3d0.0/kgsl/kgsl-3d0/pwrscale/trustzone/governor);
			if [ "$GPU_GOV" != "performance" ]; then
				echo "performance" > /sys/devices/platform/kgsl-3d0.0/kgsl/kgsl-3d0/pwrscale/trustzone/governor;
			fi;
		;;
		*)
			gpu_governor=ondemand;
		;;
	esac;
fi;

echo ${gpu_governor};

