#!/sbin/busybox sh

# $1 - "scheduler"
# $2 - value=

if [ "a$2" == "a" ]; then
        echo $scheduler;
else
        scheduler=$2;
        echo "$scheduler";
fi;

BLOCK_GOV=cfq;

SCHED_SET()
{
	echo "$BLOCK_GOV" > /sys/block/mmcblk0/queue/scheduler;
        echo "$BLOCK_GOV" > /sys/block/mmcblk1/queue/scheduler;
}

case "${scheduler}" in
	cfq)
		BLOCK_GOV=cfq;
	;;
	bfq)
		BLOCK_GOV=bfq;
	;;
	deadline)
		BLOCK_GOV=deadline;
	;;
	noop)
		BLOCK_GOV=noop;
	;;
	row)
		BLOCK_GOV=row;
	;;
	sio)
		BLOCK_GOV=sio;
	;;
        sioplus)
		BLOCK_GOV=sioplus;
	;;
	zen)
		BLOCK_GOV=zen;
	;;
        vr)
		BLOCK_GOV=vr;
	;;
	fiops)
		BLOCK_GOV=fiops;
	;;
        fifo)
		BLOCK_GOV=fifo;
	;;
        tripndroid)
		BLOCK_GOV=tripndroid;
	;;
	*)
		scheduler=cfq;
		BLOCK_GOV=cfq;
	;;
esac;
SCHED_SET;
